name: check

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # Cargo build - Only chrono (default features)
      - name: Build - Default
        run: cargo build

      # Cargo build - No features
      - name: Build - No features
        run: cargo build --no-default-features

      # Cargo build - Only 
      - name: Build - Only time feature
        run: cargo build --no-default-features --features=reg

      # Cargo build - Only 
      - name: Build - Only time feature
        run: cargo build --no-default-features --features=wmis

      # Cargo build - All features
      - name: Build - All features
        run: cargo build --all-features

  # test:
  #   name: Run tests
  #   runs-on: windows-2019
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable

      # Test on default features
      # - name: Test - All targets
      #   run: cargo test --all-targets

      # Test - Only tests with the reg crate
      # - name: Test - Only tests with the reg crate
      #   run: cargo test --tests --no-default-features --features=reg

      #  Test - Only tests with the wmis crate
      # - name: Test - Only tests with the wmis crate
      #   run: cargo test --tests --features=wmis

  fmt:
    name: Rustfmt
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run format check
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy -- -D warnings